services:
  - type: web
    name: social-media-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
