from django.shortcuts import render

# Create your views here.
from rest_framework import generics
from .models import Book
from .serializers import BookSerializer
from rest_framework import viewsets

class BookList(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookViewSet(viewsets.ModelViewSet):
    """
    BookViewSet handles all CRUD operations for Book objects.
    
    Authentication:
    - Requires TokenAuthentication (user must include 'Authorization: Token <token>' header).
    - Only authenticated users can access these endpoints.

    Available Endpoints (auto-generated by router):
    - GET    /api/books_all/         -> List all books
    - POST   /api/books_all/         -> Create a new book
    - GET    /api/books_all/<id>/    -> Retrieve a book by ID
    - PUT    /api/books_all/<id>/    -> Update a book
    - DELETE /api/books_all/<id>/    -> Delete a book
    """

    queryset = Book.objects.all()
    serializer_class = BookSerializer